# .SYNOPSIS
# Generates a random Diceware-style passphrase using the EFF large wordlist.
#
# .DESCRIPTION
# Loaded by One Identity Active Roles as a Script Module bound to a Policy
# Object. The onGetEffectivePolicy event handler is invoked by the Active
# Roles policy engine to server-side generate the value of the edsaPassword
# attribute on user objects.
#
# Randomness comes from System.Security.Cryptography.RandomNumberGenerator
# via Get-SecureRandomInt, which uses rejection sampling to produce a
# uniform integer over [0, MaxExclusive) without modulo bias.
#
# .NOTES
# Word list: Electronic Frontier Foundation,
# "EFF Large Wordlist for Passphrases"
# https://www.eff.org/dice
# Licensed under CC BY (https://creativecommons.org/licenses/by/4.0/)
# Source file:
# https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt
# The wordlist is cached locally in the ProgramData folder, and verified
# against the online source at least every -WordListRefreshIntervalDays days
# unless -SkipWordListUpdate is used.
#
# Portions of this script (notably Get-SecureRandomInt) were drafted with
# AI assistance and have been reviewed and tested by a human.
#
# .NOTES Logging
# Warning and Error events are always written to the Active Roles event log
# via the intrinsic $EventLog object (EventLog.ReportEvent). Information-
# level events are suppressed by default to keep the AR event log quiet.
# To enable them while debugging, set $script:LogInfoToEventLog = $true
# below.
#
# .NOTES Version
# The running version is exposed as $script:ScriptVersion. Bump it on each
# release and tag the matching git commit (e.g. v1.0.0). The accompanying
# checksums.txt is regenerated by the "Update checksums" VS Code task and
# the .ps1 file itself can be Authenticode-signed via the "Sign PowerShell
# script" VS Code task.

$script:ScriptVersion = '1.0.0'

# Set to $true to emit Information-level events to the Active Roles event
# log (cache lifecycle and, if enabled in onGetEffectivePolicy, per-
# passphrase generation). Warning and Error events are always logged
# regardless of this setting.
$script:LogInfoToEventLog = $false

function Write-AREventLog {
    # .SYNOPSIS
    # Writes a message to the Active Roles event log via $EventLog.
    #
    # .DESCRIPTION
    # Dispatches to $EventLog.ReportEvent using the matching
    # EDS_EVENTLOG_*_TYPE constant from $Constants. Information-level events
    # are emitted only when $script:LogInfoToEventLog is $true. Warning and
    # Error events always go through.
    #
    # The Active Roles event log entry automatically includes request
    # context (request ID, target object name, class, GUID, source
    # container), so messages should describe what the script did, not
    # which object it acted on.
    param(
        [Parameter(Mandatory)]
        [ValidateSet('Information', 'Warning', 'Error')]
        [string]$Level,

        [Parameter(Mandatory)]
        [string]$Message,

        [string]$DetailMsg1,
        [string]$DetailMsg2
    )

    if ($Level -eq 'Information' -and -not $script:LogInfoToEventLog) {
        return
    }

    $type = switch ($Level) {
        'Information' { $Constants.EDS_EVENTLOG_INFORMATION_TYPE }
        'Warning' { $Constants.EDS_EVENTLOG_WARNING_TYPE }
        'Error' { $Constants.EDS_EVENTLOG_ERROR_TYPE }
    }

    if ($PSBoundParameters.ContainsKey('DetailMsg2')) {
        $EventLog.ReportEvent($type, $Message, $DetailMsg1, $DetailMsg2)
    }
    elseif ($PSBoundParameters.ContainsKey('DetailMsg1')) {
        $EventLog.ReportEvent($type, $Message, $DetailMsg1)
    }
    else {
        $EventLog.ReportEvent($type, $Message)
    }
}

function Get-SecureRandomInt {
    # .SYNOPSIS
    # Uniform integer in [0, MaxExclusive) using RandomNumberGenerator.
    #
    # .DESCRIPTION
    # Uses rejection sampling to keep each output value equally likely.
    # A raw 32-bit random number range (0..2^32) is not always divisible by
    # MaxExclusive. Using a naive modulo on the raw value would bias the
    # lower output values slightly. To avoid that, we compute the largest
    # multiple of MaxExclusive that fits in a 32-bit range ("bucket") and
    # discard any draw that lands above it before taking the modulo.
    param(
        [Parameter(Mandatory)]
        [ValidateRange(1, [int]::MaxValue)]
        [int]$MaxExclusive
    )

    if ($MaxExclusive -eq 1) {
        return 0
    }

    $rng = [System.Security.Cryptography.RandomNumberGenerator]::Create()
    $bytes = New-Object byte[] 4
    try {
        $n = [uint64]$MaxExclusive
        $bucket = [uint64]([math]::Floor(4294967296.0 / $n) * $n)
        do {
            $null = $rng.GetBytes($bytes)
            $r = [uint64][BitConverter]::ToUInt32($bytes, 0)
        } while ($r -ge $bucket)

        return [int]($r % $n)
    }
    finally {
        $null = $rng.Dispose()
    }
}
function Get-TitleCaseWord {
    # .SYNOPSIS
    # Converts a word to title case (first letter upper-case).
    param([string]$Word)
    if ([string]::IsNullOrEmpty($Word)) {
        return $Word
    }
    $ti = (Get-Culture).TextInfo
    return $ti.ToTitleCase($Word.ToLowerInvariant())
}
function Test-EffWordListFile {
    # .SYNOPSIS
    # Validates that a candidate file parses as a complete EFF word list.
    param([string]$Path)
    if (-not (Test-Path -LiteralPath $Path)) {
        return $false
    }
    try {
        $null = Get-EffWordListFromPath -Path $Path
        return $true
    }
    catch {
        return $false
    }
}
function Get-EffWordListFromPath {
    # .SYNOPSIS
    # Reads and parses the EFF large word list from disk.
    param([string]$Path)

    $words = New-Object 'System.Collections.Generic.List[string]'
    foreach ($line in [System.IO.File]::ReadLines($Path)) {
        if ([string]::IsNullOrWhiteSpace($line)) {
            continue
        }
        if ($line -match '^\d+\s+(.+)$') {
            [void]$words.Add($Matches[1].Trim())
        }
    }

    if ($words.Count -ne 7776) {
        throw "Expected 7776 words in EFF large wordlist; found $($words.Count) in '$Path'."
    }

    return $words.ToArray()
}
function Get-EffWordList {
    # .SYNOPSIS
    # Loads the EFF word list from a path after existence checks.
    param([string]$Path)

    if (-not (Test-Path -LiteralPath $Path)) {
        throw "Word list not found: $Path."
    }

    return (Get-EffWordListFromPath -Path $Path)
}
function Read-EffWordListMetadata {
    # .SYNOPSIS
    # Reads cache metadata JSON from disk when present and valid.
    param([string]$MetaPath)

    if (-not (Test-Path -LiteralPath $MetaPath)) {
        return $null
    }

    $raw = [System.IO.File]::ReadAllText($MetaPath)
    if ([string]::IsNullOrWhiteSpace($raw)) {
        return $null
    }

    try {
        return $raw | ConvertFrom-Json
    }
    catch {
        return $null
    }
}
function Write-EffWordListMetadata {
    # .SYNOPSIS
    # Writes cache metadata JSON alongside the cached word list.
    param(
        [string]$MetaPath,
        [datetime]$LastCheckedUtc,
        [string]$SourceUrl,
        [int]$RefreshIntervalDays,
        [string]$WordListFileName
    )

    $obj = [ordered]@{
        LastCheckedUtc      = $LastCheckedUtc.ToUniversalTime().ToString('o')
        SourceUrl           = $SourceUrl
        RefreshIntervalDays = $RefreshIntervalDays
        WordListFileName    = $WordListFileName
    }

    $json = $obj | ConvertTo-Json -Depth 3
    $dir = [System.IO.Path]::GetDirectoryName($MetaPath)
    if (-not (Test-Path -LiteralPath $dir)) {
        $null = New-Item -ItemType Directory -Path $dir -Force
    }

    $temp = [System.IO.Path]::GetTempFileName()
    try {
        $null = [System.IO.File]::WriteAllText($temp, $json, [System.Text.UTF8Encoding]::new($false))
        $null = Move-Item -LiteralPath $temp -Destination $MetaPath -Force
    }
    finally {
        if (Test-Path -LiteralPath $temp) {
            $null = Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        }
    }
}
function Test-EffWordListNeedsRefresh {
    # .SYNOPSIS
    # Determines whether the cached word list should be refreshed.
    param(
        [string]$WordListPath,
        [string]$MetaPath,
        [int]$IntervalDays
    )

    if (-not (Test-Path -LiteralPath $WordListPath)) {
        return $true
    }

    if (-not (Test-EffWordListFile -Path $WordListPath)) {
        return $true
    }

    $meta = Read-EffWordListMetadata -MetaPath $MetaPath
    if ($null -eq $meta -or [string]::IsNullOrWhiteSpace([string]$meta.LastCheckedUtc)) {
        return $true
    }

    try {
        $last = [datetime]::Parse(
            [string]$meta.LastCheckedUtc,
            $null,
            [System.Globalization.DateTimeStyles]::RoundtripKind
        )
    }
    catch {
        return $true
    }

    $elapsed = [datetime]::UtcNow - $last.ToUniversalTime()
    return ($elapsed.TotalDays -ge [double]$IntervalDays)
}
function Update-EffWordListFromWeb {
    # .SYNOPSIS
    # Downloads the EFF word list and updates local cache metadata.
    param(
        [string]$DestinationPath,
        [string]$MetaPath,
        [string]$SourceUrl,
        [int]$RefreshIntervalDays,
        [string]$WordListFileName
    )

    $dir = [System.IO.Path]::GetDirectoryName($DestinationPath)
    if (-not (Test-Path -LiteralPath $dir)) {
        $null = New-Item -ItemType Directory -Path $dir -Force
    }

    $temp = Join-Path $dir ([System.IO.Path]::GetRandomFileName() + '.download')
    try {
        Write-AREventLog -Level Information `
            -Message "Downloading EFF wordlist." `
            -DetailMsg1 "Source URL: $SourceUrl"

        $null = Invoke-WebRequest -Uri $SourceUrl -OutFile $temp -UseBasicParsing

        if (-not (Test-EffWordListFile -Path $temp)) {
            throw 'Downloaded file failed validation (expected 7776 words).'
        }

        $null = Move-Item -LiteralPath $temp -Destination $DestinationPath -Force
        $null = Write-EffWordListMetadata -MetaPath $MetaPath -LastCheckedUtc ([datetime]::UtcNow) -SourceUrl $SourceUrl -RefreshIntervalDays $RefreshIntervalDays -WordListFileName $WordListFileName

        Write-AREventLog -Level Information `
            -Message "EFF wordlist cache refreshed." `
            -DetailMsg1 "Wordlist: $DestinationPath" `
            -DetailMsg2 "Metadata: $MetaPath"
    }
    finally {
        if (Test-Path -LiteralPath $temp) {
            $null = Remove-Item -LiteralPath $temp -Force -ErrorAction SilentlyContinue
        }
    }
}
function Ensure-EffWordListCache {
    # .SYNOPSIS
    # Ensures a valid local cache exists and refreshes it when due.
    param(
        [string]$WordListPath,
        [string]$MetaPath,
        [int]$IntervalDays,
        [bool]$SkipUpdate,
        [string]$SourceUrl,
        [string]$WordListFileName
    )

    $dir = [System.IO.Path]::GetDirectoryName($WordListPath)
    if (-not (Test-Path -LiteralPath $dir)) {
        $null = New-Item -ItemType Directory -Path $dir -Force
    }

    $needs = Test-EffWordListNeedsRefresh -WordListPath $WordListPath -MetaPath $MetaPath -IntervalDays $IntervalDays

    if (-not $needs) {
        Write-AREventLog -Level Information `
            -Message "Using cached EFF wordlist (last checked within $IntervalDays days)."
        return
    }

    if ($SkipUpdate) {
        if (-not (Test-Path -LiteralPath $WordListPath)) {
            throw "Word list not found at '$WordListPath' and -SkipWordListUpdate was specified. Place eff_large_wordlist.txt there or allow an online update."
        }
        if (-not (Test-EffWordListFile -Path $WordListPath)) {
            throw "Word list at '$WordListPath' is invalid or incomplete."
        }
        Write-AREventLog -Level Information `
            -Message 'SkipWordListUpdate set: using existing wordlist without contacting the network.'
        return
    }

    try {
        $null = Update-EffWordListFromWeb -DestinationPath $WordListPath -MetaPath $MetaPath -SourceUrl $SourceUrl -RefreshIntervalDays $IntervalDays -WordListFileName $WordListFileName
    }
    catch {
        if (Test-Path -LiteralPath $WordListPath) {
            Write-AREventLog -Level Warning `
                -Message "Could not refresh EFF wordlist; using existing cache." `
                -DetailMsg1 "Source URL: $SourceUrl" `
                -DetailMsg2 "Reason: $($_.Exception.Message)"
        }
        else {
            throw
        }
    }
}

function New-Password() {
    # .SYNOPSIS
    # Generates a Diceware-style passphrase using configured options.
    #
    # .DESCRIPTION
    # Selects $NumberOfWords words from the EFF large wordlist using a
    # cryptographically secure uniform RNG, optionally title-cases them, and
    # optionally appends a single random digit to one of the words. Words are
    # joined with $WordSeparator and returned as a single string.
    #
    # .PARAMETER NumberOfWords
    # Number of words in the passphrase. Defaults to 3.
    #
    # .PARAMETER WordSeparator
    # String placed between words. Defaults to '-'.
    #
    # .PARAMETER Capitalisation
    # When $true (default), each word is title-cased.
    #
    # .PARAMETER IncludeNumber
    # When $true (default), one random digit (0-9) is appended to one of the
    # randomly chosen words.
    #
    # .PARAMETER WordListRefreshIntervalDays
    # Maximum age (in days) of the cached wordlist before it is re-downloaded
    # from the EFF. Range 1-365, default 30. Ignored when -SkipWordListUpdate
    # is set.
    #
    # .PARAMETER SkipWordListUpdate
    # When set, the script will never reach the network. A valid local
    # wordlist cache must already exist.
    param(
        [ValidateRange(1, [int]::MaxValue)]
        [int]$NumberOfWords = 3,
        [string]$WordSeparator = '-',
        [bool]$Capitalisation = $true,
        [bool]$IncludeNumber = $true,
        [ValidateRange(1, 365)]
        [int]$WordListRefreshIntervalDays = 30,
        [switch]$SkipWordListUpdate
    )

    $effWordListSourceUrl = 'https://www.eff.org/files/2016/07/18/eff_large_wordlist.txt'
    $effWordListCacheDir = Join-Path $env:ProgramData 'One Identity\Active Roles'
    $effWordListCacheFileName = 'eff_large_wordlist.txt'
    $effWordListMetadataFileName = 'eff_large_wordlist.metadata.json'

    $WordListPath = Join-Path $effWordListCacheDir $effWordListCacheFileName
    $metaPath = Join-Path $effWordListCacheDir $effWordListMetadataFileName

    $null = Ensure-EffWordListCache -WordListPath $WordListPath -MetaPath $metaPath -IntervalDays $WordListRefreshIntervalDays -SkipUpdate:$SkipWordListUpdate -SourceUrl $effWordListSourceUrl -WordListFileName $effWordListCacheFileName

    $effWords = Get-EffWordList -Path $WordListPath
    $wordCount = $effWords.Length
    $words = New-Object string[] $NumberOfWords

    for ($i = 0; $i -lt $NumberOfWords; $i++) {
        $idx = Get-SecureRandomInt -MaxExclusive $wordCount
        $w = $effWords[$idx]
        if ($Capitalisation) {
            $w = Get-TitleCaseWord -Word $w
        }
        $words[$i] = $w
    }

    if ($IncludeNumber) {
        $target = Get-SecureRandomInt -MaxExclusive $NumberOfWords
        $digit = Get-SecureRandomInt -MaxExclusive 10
        $words[$target] = $words[$target] + $digit.ToString([System.Globalization.CultureInfo]::InvariantCulture)
    }

    return ($words -join $WordSeparator)

}

function onGetEffectivePolicy($request) {
    # .SYNOPSIS
    # One Identity Active Roles "OnGetEffectivePolicy" event handler.
    #
    # .DESCRIPTION
    # Invoked by Active Roles when the UI asks for the effective policy on a
    # directory object. For user objects, this handler:
    #   1. Marks edsaPassword as server-side generated so the UI hides the
    #      manual password field.
    #   2. When Active Roles asks for the full effective policy info for
    #      edsaPassword, generates a passphrase via New-Password and returns
    #      it as the suggested value.
    #
    # The $request parameter is supplied by the Active Roles script host and
    # represents the current policy request.
    if ($request.Class -ne "user") {
        return
    }

    $null = $request.SetEffectivePolicyInfo("edsaPassword", $constants.EDS_EPI_UI_SERVER_SIDE_GENERATED, $true)

    $controlFullPolicyInfo = [string]::Empty
    try {
        $controlFullPolicyInfo = $request.GetInControl($constants.EDS_CONTROL_FULL_EFFECTIVE_POLICY_INFO)
    }
    catch {}
    if ($controlFullPolicyInfo -ne "edsaPassword") {
        return
    }

    $newPwd = New-Password -NumberOfWords 3 -WordSeparator "-" -Capitalisation $true -IncludeNumber $true

    # Per-generation audit event. Gated by $script:LogInfoToEventLog (off by
    # default) so it does not flood the AR event log in normal operation.
    # Set $script:LogInfoToEventLog = $true at the top of this script to
    # enable. The generated passphrase value is intentionally NOT logged;
    # only the fact that one was generated. The AR engine already prepends
    # the target user's context (name, GUID, container) to the entry.
    Write-AREventLog -Level Information `
        -Message "Generated a server-side passphrase for edsaPassword."

    $null = $request.SetEffectivePolicyInfo("edsaPassword", $constants.EDS_EPI_UI_GENERATED_VALUE, $newPwd)
}

# SIG # Begin signature block
# MIIgNAYJKoZIhvcNAQcCoIIgJTCCICECAQExDzANBglghkgBZQMEAgEFADB5Bgor
# BgEEAYI3AgEEoGswaTA0BgorBgEEAYI3AgEeMCYCAwEAAAQQH8w7YFlLCE63JNLG
# KX7zUQIBAAIBAAIBAAIBAAIBADAxMA0GCWCGSAFlAwQCAQUABCCbK+jw0XZjpE02
# 7v40O/TCcE0jtvzQCDJzN86RUwKoqaCCGrowggOCMIIDCaADAgECAhBu3U8l5zF9
# OYFXMTTPwdygMAoGCCqGSM49BAMDMH8xCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVU
# ZXhhczEQMA4GA1UEBwwHSG91c3RvbjEYMBYGA1UECgwPU1NMIENvcnBvcmF0aW9u
# MTQwMgYDVQQDDCtTU0wuY29tIEVWIFJvb3QgQ2VydGlmaWNhdGlvbiBBdXRob3Jp
# dHkgRUNDMB4XDTE5MDMwNzE5Mzc0NVoXDTM0MDMwMzE5Mzc0NVowezELMAkGA1UE
# BhMCVVMxDjAMBgNVBAgMBVRleGFzMRAwDgYDVQQHDAdIb3VzdG9uMREwDwYDVQQK
# DAhTU0wgQ29ycDE3MDUGA1UEAwwuU1NMLmNvbSBFViBDb2RlIFNpZ25pbmcgSW50
# ZXJtZWRpYXRlIENBIEVDQyBSMjB2MBAGByqGSM49AgEGBSuBBAAiA2IABDrQ4dqT
# 4rxW0Uk0uIEsNETSGyWTorL/T7TkHzPBJvtMekCG2uzlVG/okXNTkCmKbgXR7rcO
# uDsgCehjjKBRoBT7FuMyK45CpEFAe1DqopbneXiDXLAZzL8OI6Cz5RSpsaOCAUww
# ggFIMBIGA1UdEwEB/wQIMAYBAf8CAQAwHwYDVR0jBBgwFoAUW8pe5d7SgarNqC1k
# UbbZcpuX5k8wewYIKwYBBQUHAQEEbzBtMEkGCCsGAQUFBzAChj1odHRwOi8vd3d3
# LnNzbC5jb20vcmVwb3NpdG9yeS9TU0xjb20tUm9vdENBLUVWLUVDQy0zODQtUjEu
# Y3J0MCAGCCsGAQUFBzABhhRodHRwOi8vb2NzcHMuc3NsLmNvbTARBgNVHSAECjAI
# MAYGBFUdIAAwEwYDVR0lBAwwCgYIKwYBBQUHAwMwPQYDVR0fBDYwNDAyoDCgLoYs
# aHR0cDovL2NybHMuc3NsLmNvbS9zc2wuY29tLUVWZWNjLVJvb3RDQS5jcmwwHQYD
# VR0OBBYEFAGJlLn+tDNd8PH6hfkkRoSjV2leMA4GA1UdDwEB/wQEAwIBhjAKBggq
# hkjOPQQDAwNnADBkAjBKW+qAn7o2ks+MMe3spZnuMie8wxfrh49XUDAFv3WV9zz5
# PxlSgzQg4RFW7jk+t+4CMAK1uNn4eBJHwcBF/xX2oGa7Q+JPQw5Yd5ekolU0JIRa
# VhnPplUgG9kQmlMA+4lecDCCA/YwggN8oAMCAQICEFNH/mVzWPA4gsMaHHg2s6cw
# CgYIKoZIzj0EAwMwezELMAkGA1UEBhMCVVMxDjAMBgNVBAgMBVRleGFzMRAwDgYD
# VQQHDAdIb3VzdG9uMREwDwYDVQQKDAhTU0wgQ29ycDE3MDUGA1UEAwwuU1NMLmNv
# bSBFViBDb2RlIFNpZ25pbmcgSW50ZXJtZWRpYXRlIENBIEVDQyBSMjAeFw0yMzA5
# MTkxNzI1MDFaFw0yNjA5MTgxNzI1MDFaMIG4MQswCQYDVQQGEwJDQTEQMA4GA1UE
# CAwHT250YXJpbzEPMA0GA1UEBwwGT3R0YXdhMR4wHAYDVQQKDBVNYWRyaWFtIFNl
# cnZpY2VzIEluYy4xEjAQBgNVBAUTCTExMjYxMzYtMzEeMBwGA1UEAwwVTWFkcmlh
# bSBTZXJ2aWNlcyBJbmMuMR0wGwYDVQQPDBRQcml2YXRlIE9yZ2FuaXphdGlvbjET
# MBEGCysGAQQBgjc8AgEDEwJDQTB2MBAGByqGSM49AgEGBSuBBAAiA2IABJKGZhyL
# Uf+qUvYOJp5klIo5Dv2D517rhg2oadMcWY7YQvObKJ+M69XUWuZISbvxlZLtzcs9
# lw2oXpEnFrJZDRpRextHq+DVvhdiiJOZOfhPjaL/2w3dqdUe1qLe0vQwmqOCAYUw
# ggGBMAwGA1UdEwEB/wQCMAAwHwYDVR0jBBgwFoAUAYmUuf60M13w8fqF+SRGhKNX
# aV4wWgYIKwYBBQUHAQEETjBMMEoGCCsGAQUFBzAChj5odHRwOi8vY2VydC5zc2wu
# Y29tL1NTTGNvbS1TdWJDQS1FVi1jb2RlU2lnbmluZy1FQ0MtMzg0LVIyLmNlcjBf
# BgNVHSAEWDBWMAcGBWeBDAEDMA0GCyqEaAGG9ncCBQEHMDwGDCsGAQQBgqkwAQMD
# AjAsMCoGCCsGAQUFBwIBFh5odHRwczovL3d3dy5zc2wuY29tL3JlcG9zaXRvcnkw
# EwYDVR0lBAwwCgYIKwYBBQUHAwMwTwYDVR0fBEgwRjBEoEKgQIY+aHR0cDovL2Ny
# bHMuc3NsLmNvbS9TU0xjb20tU3ViQ0EtRVYtY29kZVNpZ25pbmctRUNDLTM4NC1S
# Mi5jcmwwHQYDVR0OBBYEFHiwVSjHMXieTj9vmEoTPpFIvJ4IMA4GA1UdDwEB/wQE
# AwIHgDAKBggqhkjOPQQDAwNoADBlAjEAmNwghnB6MJvDuhZn/dihQfY4xDkl+2x+
# YvWt3Kv9mavaJw+lJ6D0t4NAuHluEq+TAjAtzldhyNj3KiBCvLNZzRPfPsC3BEI0
# kwY439LzmEJjp0ZCUcYfFa/pNyxUeaF2DJ0wggWNMIIEdaADAgECAhAOmxiO+dAt
# 5+/bUOIIQBhaMA0GCSqGSIb3DQEBDAUAMGUxCzAJBgNVBAYTAlVTMRUwEwYDVQQK
# EwxEaWdpQ2VydCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xJDAiBgNV
# BAMTG0RpZ2lDZXJ0IEFzc3VyZWQgSUQgUm9vdCBDQTAeFw0yMjA4MDEwMDAwMDBa
# Fw0zMTExMDkyMzU5NTlaMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2Vy
# dCBJbmMxGTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lD
# ZXJ0IFRydXN0ZWQgUm9vdCBHNDCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoC
# ggIBAL/mkHNo3rvkXUo8MCIwaTPswqclLskhPfKK2FnC4SmnPVirdprNrnsbhA3E
# MB/zG6Q4FutWxpdtHauyefLKEdLkX9YFPFIPUh/GnhWlfr6fqVcWWVVyr2iTcMKy
# unWZanMylNEQRBAu34LzB4TmdDttceItDBvuINXJIB1jKS3O7F5OyJP4IWGbNOsF
# xl7sWxq868nPzaw0QF+xembud8hIqGZXV59UWI4MK7dPpzDZVu7Ke13jrclPXuU1
# 5zHL2pNe3I6PgNq2kZhAkHnDeMe2scS1ahg4AxCN2NQ3pC4FfYj1gj4QkXCrVYJB
# MtfbBHMqbpEBfCFM1LyuGwN1XXhm2ToxRJozQL8I11pJpMLmqaBn3aQnvKFPObUR
# WBf3JFxGj2T3wWmIdph2PVldQnaHiZdpekjw4KISG2aadMreSx7nDmOu5tTvkpI6
# nj3cAORFJYm2mkQZK37AlLTSYW3rM9nF30sEAMx9HJXDj/chsrIRt7t/8tWMcCxB
# YKqxYxhElRp2Yn72gLD76GSmM9GJB+G9t+ZDpBi4pncB4Q+UDCEdslQpJYls5Q5S
# UUd0viastkF13nqsX40/ybzTQRESW+UQUOsxxcpyFiIJ33xMdT9j7CFfxCBRa2+x
# q4aLT8LWRV+dIPyhHsXAj6KxfgommfXkaS+YHS312amyHeUbAgMBAAGjggE6MIIB
# NjAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBTs1+OC0nFdZEzfLmc/57qYrhwP
# TzAfBgNVHSMEGDAWgBRF66Kv9JLLgjEtUYunpyGd823IDzAOBgNVHQ8BAf8EBAMC
# AYYweQYIKwYBBQUHAQEEbTBrMCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdp
# Y2VydC5jb20wQwYIKwYBBQUHMAKGN2h0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNv
# bS9EaWdpQ2VydEFzc3VyZWRJRFJvb3RDQS5jcnQwRQYDVR0fBD4wPDA6oDigNoY0
# aHR0cDovL2NybDMuZGlnaWNlcnQuY29tL0RpZ2lDZXJ0QXNzdXJlZElEUm9vdENB
# LmNybDARBgNVHSAECjAIMAYGBFUdIAAwDQYJKoZIhvcNAQEMBQADggEBAHCgv0Nc
# Vec4X6CjdBs9thbX979XB72arKGHLOyFXqkauyL4hxppVCLtpIh3bb0aFPQTSnov
# Lbc47/T/gLn4offyct4kvFIDyE7QKt76LVbP+fT3rDB6mouyXtTP0UNEm0Mh65Zy
# oUi0mcudT6cGAxN3J0TU53/oWajwvy8LpunyNDzs9wPHh6jSTEAZNUZqaVSwuKFW
# juyk1T3osdz9HNj0d1pcVIxv76FQPfx2CWiEn2/K2yCNNWAcAgPLILCsWKAOQGPF
# mCLBsln1VWvPJ6tsds5vIy30fnFqI2si/xK4VC0nftg62fC2h5b9W9FcrBjDTZ9z
# twGpn1eqXijiuZQwgga0MIIEnKADAgECAhANx6xXBf8hmS5AQyIMOkmGMA0GCSqG
# SIb3DQEBCwUAMGIxCzAJBgNVBAYTAlVTMRUwEwYDVQQKEwxEaWdpQ2VydCBJbmMx
# GTAXBgNVBAsTEHd3dy5kaWdpY2VydC5jb20xITAfBgNVBAMTGERpZ2lDZXJ0IFRy
# dXN0ZWQgUm9vdCBHNDAeFw0yNTA1MDcwMDAwMDBaFw0zODAxMTQyMzU5NTlaMGkx
# CzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4
# RGlnaUNlcnQgVHJ1c3RlZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBTSEEyNTYg
# MjAyNSBDQTEwggIiMA0GCSqGSIb3DQEBAQUAA4ICDwAwggIKAoICAQC0eDHTCphB
# cr48RsAcrHXbo0ZodLRRF51NrY0NlLWZloMsVO1DahGPNRcybEKq+RuwOnPhof6p
# vF4uGjwjqNjfEvUi6wuim5bap+0lgloM2zX4kftn5B1IpYzTqpyFQ/4Bt0mAxAHe
# HYNnQxqXmRinvuNgxVBdJkf77S2uPoCj7GH8BLuxBG5AvftBdsOECS1UkxBvMgEd
# gkFiDNYiOTx4OtiFcMSkqTtF2hfQz3zQSku2Ws3IfDReb6e3mmdglTcaarps0wjU
# jsZvkgFkriK9tUKJm/s80FiocSk1VYLZlDwFt+cVFBURJg6zMUjZa/zbCclF83bR
# VFLeGkuAhHiGPMvSGmhgaTzVyhYn4p0+8y9oHRaQT/aofEnS5xLrfxnGpTXiUOeS
# LsJygoLPp66bkDX1ZlAeSpQl92QOMeRxykvq6gbylsXQskBBBnGy3tW/AMOMCZIV
# NSaz7BX8VtYGqLt9MmeOreGPRdtBx3yGOP+rx3rKWDEJlIqLXvJWnY0v5ydPpOjL
# 6s36czwzsucuoKs7Yk/ehb//Wx+5kMqIMRvUBDx6z1ev+7psNOdgJMoiwOrUG2Zd
# SoQbU2rMkpLiQ6bGRinZbI4OLu9BMIFm1UUl9VnePs6BaaeEWvjJSjNm2qA+sdFU
# eEY0qVjPKOWug/G6X5uAiynM7Bu2ayBjUwIDAQABo4IBXTCCAVkwEgYDVR0TAQH/
# BAgwBgEB/wIBADAdBgNVHQ4EFgQU729TSunkBnx6yuKQVvYv1Ensy04wHwYDVR0j
# BBgwFoAU7NfjgtJxXWRM3y5nP+e6mK4cD08wDgYDVR0PAQH/BAQDAgGGMBMGA1Ud
# JQQMMAoGCCsGAQUFBwMIMHcGCCsGAQUFBwEBBGswaTAkBggrBgEFBQcwAYYYaHR0
# cDovL29jc3AuZGlnaWNlcnQuY29tMEEGCCsGAQUFBzAChjVodHRwOi8vY2FjZXJ0
# cy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVzdGVkUm9vdEc0LmNydDBDBgNVHR8E
# PDA6MDigNqA0hjJodHRwOi8vY3JsMy5kaWdpY2VydC5jb20vRGlnaUNlcnRUcnVz
# dGVkUm9vdEc0LmNybDAgBgNVHSAEGTAXMAgGBmeBDAEEAjALBglghkgBhv1sBwEw
# DQYJKoZIhvcNAQELBQADggIBABfO+xaAHP4HPRF2cTC9vgvItTSmf83Qh8WIGjB/
# T8ObXAZz8OjuhUxjaaFdleMM0lBryPTQM2qEJPe36zwbSI/mS83afsl3YTj+IQhQ
# E7jU/kXjjytJgnn0hvrV6hqWGd3rLAUt6vJy9lMDPjTLxLgXf9r5nWMQwr8Myb9r
# EVKChHyfpzee5kH0F8HABBgr0UdqirZ7bowe9Vj2AIMD8liyrukZ2iA/wdG2th9y
# 1IsA0QF8dTXqvcnTmpfeQh35k5zOCPmSNq1UH410ANVko43+Cdmu4y81hjajV/gx
# dEkMx1NKU4uHQcKfZxAvBAKqMVuqte69M9J6A47OvgRaPs+2ykgcGV00TYr2Lr3t
# y9qIijanrUR3anzEwlvzZiiyfTPjLbnFRsjsYg39OlV8cipDoq7+qNNjqFzeGxcy
# tL5TTLL4ZaoBdqbhOhZ3ZRDUphPvSRmMThi0vw9vODRzW6AxnJll38F0cuJG7uEB
# YTptMSbhdhGQDpOXgpIUsWTjd6xpR6oaQf/DJbg3s6KCLPAlZ66RzIg9sC+NJpud
# /v4+7RWsWCiKi9EOLLHfMR2ZyJ/+xhCx9yHbxtl5TPau1j/1MIDpMPx0LckTetiS
# uEtQvLsNz3Qbp7wGWqbIiOWCnb5WqxL3/BAPvIXKUjPSxyZsq8WhbaM2tszWkPZP
# ubdcMIIG7TCCBNWgAwIBAgIQCoDvGEuN8QWC0cR2p5V0aDANBgkqhkiG9w0BAQsF
# ADBpMQswCQYDVQQGEwJVUzEXMBUGA1UEChMORGlnaUNlcnQsIEluYy4xQTA/BgNV
# BAMTOERpZ2lDZXJ0IFRydXN0ZWQgRzQgVGltZVN0YW1waW5nIFJTQTQwOTYgU0hB
# MjU2IDIwMjUgQ0ExMB4XDTI1MDYwNDAwMDAwMFoXDTM2MDkwMzIzNTk1OVowYzEL
# MAkGA1UEBhMCVVMxFzAVBgNVBAoTDkRpZ2lDZXJ0LCBJbmMuMTswOQYDVQQDEzJE
# aWdpQ2VydCBTSEEyNTYgUlNBNDA5NiBUaW1lc3RhbXAgUmVzcG9uZGVyIDIwMjUg
# MTCCAiIwDQYJKoZIhvcNAQEBBQADggIPADCCAgoCggIBANBGrC0Sxp7Q6q5gVrMr
# V7pvUf+GcAoB38o3zBlCMGMyqJnfFNZx+wvA69HFTBdwbHwBSOeLpvPnZ8ZN+vo8
# dE2/pPvOx/Vj8TchTySA2R4QKpVD7dvNZh6wW2R6kSu9RJt/4QhguSssp3qome7M
# rxVyfQO9sMx6ZAWjFDYOzDi8SOhPUWlLnh00Cll8pjrUcCV3K3E0zz09ldQ//nBZ
# ZREr4h/GI6Dxb2UoyrN0ijtUDVHRXdmncOOMA3CoB/iUSROUINDT98oksouTMYFO
# nHoRh6+86Ltc5zjPKHW5KqCvpSduSwhwUmotuQhcg9tw2YD3w6ySSSu+3qU8DD+n
# igNJFmt6LAHvH3KSuNLoZLc1Hf2JNMVL4Q1OpbybpMe46YceNA0LfNsnqcnpJeIt
# K/DhKbPxTTuGoX7wJNdoRORVbPR1VVnDuSeHVZlc4seAO+6d2sC26/PQPdP51ho1
# zBp+xUIZkpSFA8vWdoUoHLWnqWU3dCCyFG1roSrgHjSHlq8xymLnjCbSLZ49kPmk
# 8iyyizNDIXj//cOgrY7rlRyTlaCCfw7aSUROwnu7zER6EaJ+AliL7ojTdS5PWPsW
# eupWs7NpChUk555K096V1hE0yZIXe+giAwW00aHzrDchIc2bQhpp0IoKRR7YufAk
# prxMiXAJQ1XCmnCfgPf8+3mnAgMBAAGjggGVMIIBkTAMBgNVHRMBAf8EAjAAMB0G
# A1UdDgQWBBTkO/zyMe39/dfzkXFjGVBDz2GM6DAfBgNVHSMEGDAWgBTvb1NK6eQG
# fHrK4pBW9i/USezLTjAOBgNVHQ8BAf8EBAMCB4AwFgYDVR0lAQH/BAwwCgYIKwYB
# BQUHAwgwgZUGCCsGAQUFBwEBBIGIMIGFMCQGCCsGAQUFBzABhhhodHRwOi8vb2Nz
# cC5kaWdpY2VydC5jb20wXQYIKwYBBQUHMAKGUWh0dHA6Ly9jYWNlcnRzLmRpZ2lj
# ZXJ0LmNvbS9EaWdpQ2VydFRydXN0ZWRHNFRpbWVTdGFtcGluZ1JTQTQwOTZTSEEy
# NTYyMDI1Q0ExLmNydDBfBgNVHR8EWDBWMFSgUqBQhk5odHRwOi8vY3JsMy5kaWdp
# Y2VydC5jb20vRGlnaUNlcnRUcnVzdGVkRzRUaW1lU3RhbXBpbmdSU0E0MDk2U0hB
# MjU2MjAyNUNBMS5jcmwwIAYDVR0gBBkwFzAIBgZngQwBBAIwCwYJYIZIAYb9bAcB
# MA0GCSqGSIb3DQEBCwUAA4ICAQBlKq3xHCcEua5gQezRCESeY0ByIfjk9iJP2zWL
# pQq1b4URGnwWBdEZD9gBq9fNaNmFj6Eh8/YmRDfxT7C0k8FUFqNh+tshgb4O6Lgj
# g8K8elC4+oWCqnU/ML9lFfim8/9yJmZSe2F8AQ/UdKFOtj7YMTmqPO9mzskgiC3Q
# YIUP2S3HQvHG1FDu+WUqW4daIqToXFE/JQ/EABgfZXLWU0ziTN6R3ygQBHMUBaB5
# bdrPbF6MRYs03h4obEMnxYOX8VBRKe1uNnzQVTeLni2nHkX/QqvXnNb+YkDFkxUG
# tMTaiLR9wjxUxu2hECZpqyU1d0IbX6Wq8/gVutDojBIFeRlqAcuEVT0cKsb+zJNE
# suEB7O7/cuvTQasnM9AWcIQfVjnzrvwiCZ85EE8LUkqRhoS3Y50OHgaY7T/lwd6U
# Arb+BOVAkg2oOvol/DJgddJ35XTxfUlQ+8Hggt8l2Yv7roancJIFcbojBcxlRcGG
# 0LIhp6GvReQGgMgYxQbV1S3CrWqZzBt1R9xJgKf47CdxVRd/ndUlQ05oxYy2zRWV
# FjF7mcr4C34Mj3ocCVccAvlKV9jEnstrniLvUxxVZE/rptb7IRE2lskKPIJgbaP5
# t2nGj/ULLi49xTcBZU8atufk+EMF/cWuiC7POGT75qaL6vdCvHlshtjdNXOCIUjs
# arfNZzGCBNAwggTMAgEBMIGPMHsxCzAJBgNVBAYTAlVTMQ4wDAYDVQQIDAVUZXhh
# czEQMA4GA1UEBwwHSG91c3RvbjERMA8GA1UECgwIU1NMIENvcnAxNzA1BgNVBAMM
# LlNTTC5jb20gRVYgQ29kZSBTaWduaW5nIEludGVybWVkaWF0ZSBDQSBFQ0MgUjIC
# EFNH/mVzWPA4gsMaHHg2s6cwDQYJYIZIAWUDBAIBBQCggYQwGAYKKwYBBAGCNwIB
# DDEKMAigAoAAoQKAADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEE
# AYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAvBgkqhkiG9w0BCQQxIgQg7a4YfKpWv1nH
# YAV77P8vHro40acOs+KcCjK2IYnCF+UwCwYHKoZIzj0CAQUABGgwZgIxAPD8kSS5
# +sz25o12XlECZM7Tm9Dccic2g/Wa0nODMLSqh0zpU562yiYhvGWbW2TlMQIxAKeP
# 0Zh+m6052Cu5xvA8lqM0dP1zpOicepe9zxKk+2VXMDkppqqGDsrdDg8Cm958EaGC
# AyYwggMiBgkqhkiG9w0BCQYxggMTMIIDDwIBATB9MGkxCzAJBgNVBAYTAlVTMRcw
# FQYDVQQKEw5EaWdpQ2VydCwgSW5jLjFBMD8GA1UEAxM4RGlnaUNlcnQgVHJ1c3Rl
# ZCBHNCBUaW1lU3RhbXBpbmcgUlNBNDA5NiBTSEEyNTYgMjAyNSBDQTECEAqA7xhL
# jfEFgtHEdqeVdGgwDQYJYIZIAWUDBAIBBQCgaTAYBgkqhkiG9w0BCQMxCwYJKoZI
# hvcNAQcBMBwGCSqGSIb3DQEJBTEPFw0yNjA1MjYxODQwNTFaMC8GCSqGSIb3DQEJ
# BDEiBCDbKbdFGmBR9iCA8LrdlWr2Y+1zh00hoXUYhGE0fDyDQjANBgkqhkiG9w0B
# AQEFAASCAgCYcaJX1IEWK06+QU7P425tOnPB9umCe83taouXLDw+omlCOXIj5umd
# a1KFFKbOm1ApEO8gFwTYTGiMPG9h3oL1eszn+BHBwtd41eWYOZ4kKaPaPVBWRyVk
# Dyq9RVWlABDkfcwonrAm6b6vScWpcLCx4Rb1BEePXpkOnVq3DnjKnwZKxMFM6F8E
# UjIhPdtciJMUmve1Nw8njqhugy9fYRgGgaReBQAudU0r5nciBnanARyWWtyt+3Zh
# Fdy0XNfL7XMW48w1rdYijrl+KE1+bpfHKgJ/TZ+f7bE3nUuLsKXkpxaNtHex7pKT
# e1p6qBWqJkUhnLWY7JDzHxgR6/W8n3T6WVAFlVg3ou3Jyom/j6x0cg+Fm+DzmW3N
# FZjhtdTEGir3vR+5GYDq57PGVDfaDaI/9n1tVSOeX+OsK8JWjwOj77Jj7x8iXbDk
# SbxrJmTlJQRcFsh2pSpx+tYpsBTe+hGCHC7Sq/qK2K2Er5fyWM08EcsULj5GePj/
# gulmA7YiZpHjMS3KCeahhgJeF8DXQdTeak8wueHRrLdKlYz24ApUIzS6skYfHOzS
# XHxcxtuYB8YB2h49iJVEPzqGxxr3K4RDqDDuJgyNmDoJJgpf9Prz7YqmPscUn5PH
# 6Uckg1Z63lSji4cusTwrUBIRPaWbOqd0qSwohYuC/0gYcixob0zMQQ==
# SIG # End signature block
